[project]
name = "deepseek-quickstart-fork"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jieba>=0.42.1",
    "openai>=1.84.0",
    "pymilvus>=2.5.10",
    "sentence-transformers>=4.1.0",
]
